services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: rezepte_db
      POSTGRES_USER: rezepte_user
      POSTGRES_PASSWORD: rezepte_password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --lc-collate=C.UTF-8 --lc-ctype=C.UTF-8"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U rezepte_user -d rezepte_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  # One-time migration service
  migrate:
    build:
      context: .
      dockerfile: docker/Dockerfile.migrate
    environment:
      DATABASE_URL: postgresql://rezepte_user:rezepte_password@postgres/rezepte_db
      DBF_FILE: Rezepte.dbf
    volumes:
      - ./Rezepte.dbf:/app/Rezepte.dbf:ro
    depends_on:
      postgres:
        condition: service_healthy
    profiles:
      - migrate

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      DATABASE_URL: postgresql://rezepte_user:rezepte_password@postgres/rezepte_db
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: