# Production override for docker-compose.yml
# Usage: docker compose -f docker-compose.yml -f docker-compose.prod.yml up -d

services:
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # For SSL certificates
    depends_on:
      - web
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  postgres:
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups  # For database backups
    environment:
      - POSTGRES_DB=rezepte_db
      - POSTGRES_USER=rezepte_user
      - POSTGRES_PASSWORD=${DB_PASSWORD:-rezepte_password}  # Use env var in production
    # Uncomment for external access (be careful!)
    # ports:
    #   - "127.0.0.1:5432:5432"  # Only localhost access

  web:
    restart: unless-stopped
    environment:
      - DATABASE_URL=postgresql://rezepte_user:${DB_PASSWORD:-rezepte_password}@postgres/rezepte_db
      # - SENTRY_DSN=${SENTRY_DSN}  # Uncomment for error tracking
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    # Remove port exposure - access via nginx only
    expose:
      - "8000"
    volumes:
      - ./uploads:/app/uploads  # Persistent image storage
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/recipes"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  # Remove migration service in production
  migrate:
    profiles:
      - migrate
      - never  # Prevent accidental running in production